#!/bin/bash

# Este script es ejecutado por root y crea el usuario SIadmin
# Le da los permisos de sudoer para useradd, userdel, usermod
# crea las crontab del admin
# manipula la sudoers
# crea SIGTdb, impulsa su DDL, la dona al admin

# Carpeta de trabajo : /root/SI
# Copiar este script SIinst a /root/SI/, y chmod u+x SIinst, y ejecutar.

# Bienvenida
msg='Bienvenido a la instalacion de SI !'
yad --center --width=400 --height=300 --no-buttons --undecorated --borders=0 --on-top --image=./imagenes/siadamin.jpg --window-icon=./imagenes/icon.jpg --timeout=4

icoa=c

# Creo usuario SIadmin, su shell es SImenu (ejecuta en login)
# SIadmin debe tener home por el tema logs (/home/SIadmin/log) y por su bin.
useradd -d /home/SISFTadmin -m -s /home/SISFTadmin/bin/SISFTmenu -c "Administrador de SISFT" SISFTadmin 2>/dev/null
res=$(echo $?)
if test $res -eq 9; then
  msj='SISFTadmin ya existia en el sistema y sera eliminado'
  if test $icoa == "c"; then 
    read  -p "$msj"
  else
    dialog --msgbox "$msj" 7 43
  fi
  userdel -r SISFTadmin
  useradd -d /home/SISFTadmin -m -s /home/SISFTadmin/bin/SISFTmenu -c "Administrador de SISFT" SISFTadmin 2>/dev/null
fi
msg='SISFTadmin fue creado con exito!'
if test $icoa == "c"; then 
    read  -p "$msg"
else
    dialog --msgbox "$msg" 5 43
fi

# Area contraseña
msg='SISFTadmin - Por favor,Ingrese su nueva contraseña :'
msgV='SISFTadmin - Por favor, re ingrese su nueva contraseña :'
msgPwdOk='Su clave se ha ingresado con exito'
msgPwdErr='Las claves no coinciden, vuelva a intentarlo'
while true; do
  if test $icoa == "c"; then
    read -s -p "$msg" contr # -s : hace que no se vea en pantalla
    echo
    read -s -p "$msgV" nuevacontr
    echo
    if [ "$contr" == "$nuevacontr" ]; then
      if test -z "$contr"; then
        read -p "contrasena vacia" x
        continue
      fi
      read -p "$msgPwdOk"
      break
    else
      read -p "$msgPwdErr"
    fi
  else
    dialog --insecure --mixedform '* Formulario de ingreso de clave *' 17 45 7 \
    'Clave :' 2 5 '' 2 19 15 20 1 \
    'Repita Clave :' 4 5 '' 4 19 15 20 1 2>sd
    contr=$(head -1 sd)
    nuevacontr=$(tail -1 sd)
    if [ "$contr" == "$nuevacontr" ]; then
      if test -z "$contr"; then
        dialog --msgbox "clave vacia" 7 43
        continue
      fi
      dialog --msgbox "$msgPwdOk" 7 43
      break
    else
      dialog --msgbox "$msgPwdErr" 7 43
    fi
  fi # if test $icoa == "c"; then
done
echo SISFTadmin:$contr | chpasswd

echo
ver='Insertando permisos ABM para usuario & grupo..!'
if test $icoa == "c"; then 
    read  -p "$ver"
else
    dialog --msgbox "$ver" 6 43
fi
# entradas de /etc/sudoers para SIadmin
grep 'Comienzo permisos del subsistema SI' /etc/sudoers
if test $? -eq 1; then
  echo >>/etc/sudoers
  echo '#' >>/etc/sudoers
  echo '# Comienzo permisos del subsistema SI' >>/etc/sudoers
  echo 'SISFTadmin '$HOSTNAME' = (ALL) NOPASSWD: '$(which useradd) >>/etc/sudoers
  echo 'SISFTadmin '$HOSTNAME' = (ALL) NOPASSWD: '$(which userdel) >>/etc/sudoers
  echo 'SISFTadmin '$HOSTNAME' = (ALL) NOPASSWD: '$(which usermod) >>/etc/sudoers
  echo 'SISFTadmin '$HOSTNAME' = (ALL) NOPASSWD: '$(which groupadd) >>/etc/sudoers
  echo 'SISFTadmin '$HOSTNAME' = (ALL) NOPASSWD: '$(which groupdel) >>/etc/sudoers
  echo 'SISFTadmin '$HOSTNAME' = (ALL) NOPASSWD: '$(which groupmod) >>/etc/sudoers
  echo 'SISFTadmin '$HOSTNAME' = (ALL) NOPASSWD: /usr/bin/passwd SIFT*' >>/etc/sudoers
fi

echo
ver='Copiando SISFTMenu al home de SISFTadmin y entregandole permiso de usuario dueño...'
if test $icoa == "c"; then 
    read  -p "$ver"
else
    dialog --msgbox "$ver" 7 43
fi

mkdir /home/SISFTadmin/bin
echo
ver='Creado el directorio bin a SISFTadmin...'
if test $icoa == "c"; then 
    read  -p "$ver"
else
    dialog --msgbox "$ver" 7 43
fi

chown SISFTadmin:SISFTadmin /home/SISFTadmin/bin
echo
ver='Entregada la propiedad de la carpeta a SISFTadmin...'
if test $icoa == "c"; then 
    read  -p "$ver"
else
    dialog --msgbox "$ver" 7 43
fi

cp /root/SI/SISFTmenu /home/SISFTadmin/bin
echo
ver='Copiado SISFTMenu al directorio bin...'
if test $icoa == "c"; then 
    read  -p "$ver"
else
    dialog --msgbox "$ver" 6 43
fi

chown SISFTadmin:SISFTadmin /home/SISFTadmin/bin/SISFTmenu
ver='Transladados permisos de usuario dueño de SISFTMenu...'
if test $icoa == "c"; then 
    read  -p "$ver"
else
    dialog --msgbox "$ver" 7 43
fi

echo
chmod u+x /home/SISFTadmin/bin/SISFTmenu
ver='Asignando permiso de ejecucion al dueño..'
if test $icoa == "c"; then 
    read  -p "$ver"
else
    dialog --msgbox "$ver" 7 43
fi


